### ISSUE TITLE
Authentication fails with valid username/password

### ISSUE THREAD

**Issue by russelkrause** [jonathanpotts/Ring#1] opened 2018-06-06 04:55 UTC
Hi!

Thanks very much for porting this to .net core!

Can you confirm that the Initialize(username,password) method is still working, or if I am missing a step?  I am getting the following message when sending the username/password I use to connect to Ring through my iOS App and online at https://ring.com/account/activity

var ring = await RingClient.CreateAsync(username, password);

The Ring API returned the following error: Unauthorized

Russel

**Comment by jonathanpotts** [comment] 2018-06-06 05:49
I know what the issue is (they changed the way authentication works). I'll try to have an update out soon.

**Comment by russelkrause** [comment] 2018-06-06 19:49
Thanks!  Most appreciative!

Russel

**Comment by jonathanpotts** [comment] 2018-06-07 03:40
Fixed in version 2.0.0.

Thanks to @Sfinx for information regarding new auth method: https://github.com/davglass/doorbot/issues/16#issuecomment-393551422

**Closed as completed by jonathanpotts** 2018-06-07 03:40 UTC
Labels: bug

**Comment by russelkrause** [comment] 2018-06-07 14:40
Fantastic!

Thanks, Russel
